networks:
  loki-net:
    driver: bridge

services:
  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log/:/var/log/
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    networks:
      - loki-net

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yaml
    networks:
      - loki-net
    depends_on:
      - promtail

  grafana:
    image: grafana/grafana:latest
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
    ports:
      - "3000:3000"
    networks:
      - loki-net
    depends_on:
      - loki
