version: '3'

# Define a custom network
networks:
  app-network:
    driver: bridge

services:
  web:
    # todo: swap over to registry
    image: tedbalashov/tedpod:cloudidebackend
    container_name: web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # todo: change to relative pathing
      - /home/ec2-user/.aws:/root/.aws:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
    networks:
      app-network:
        aliases:
          - backend

  celery-worker:
    image: tedbalashov/tedpod:cloudidebackend
    container_name: celery-worker
    env_file:
      - .env
    volumes:
      # - ~/.aws:/root/.aws:ro
      - /home/ec2-user/.aws:/root/.aws:ro
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network

  celery-beat:
    image: tedbalashov/tedpod:cloudidebackend
    container_name: celery-beat
    env_file:
      - .env
    volumes:
      # - ~/.aws:/root/.aws:ro
      - /home/ec2-user/.aws:/root/.aws:ro
    command: celery -A app.celery_app.celery_app beat --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

  nginx:
    image: tedbalashov/tedpod:cloudidenginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - /home/ec2-user/.certs/:/ssl/
    platform: linux/amd64
    networks:
      - app-network