networks:
  app-network:
    driver: bridge

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      # - /c/Users/CharlesJester/.aws:/root/.aws:ro
      - ${AWS_FOLDER}:/root/.aws:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
    networks:
      app-network:
        aliases:
          - backend


  celery-worker:
    build: ./backend
    container_name: celery-worker
    env_file:
      - .env
    volumes:
      - ${AWS_FOLDER}:/root/.aws:ro
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network

  celery-beat:
    build: ./backend
    container_name: celery-beat
    env_file:
      - .env
    volumes:
      - ${AWS_FOLDER}:/root/.aws:ro
    command: celery -A app.celery_app.celery_app beat --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8000
    container_name: frontend
    ports:
      - "3500:3500"
    env_file:
      - ./.env
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - PORT=3500
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      app-network:
        aliases:
          - frontend

  redis:
    image: redis:alpine
    pull_policy: always
    container_name: redis
    networks:
      - app-network

  nginx:
    build: ./proxy
    container_name: nginx
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    volumes:
      - ${CERTS_FOLDER}:/.certs/
    platform: linux/amd64
    depends_on:
      - backend
      - frontend
    networks:
      - app-network