{
 "title": "Runner-Tops",
 "tags": [ "runner" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Active Runners",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count by( job) (increase(node_cpu_seconds_total[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100* (1-((sum by (job) (rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))) / (sum by (job) (rate(node_cpu_seconds_total[$__rate_interval])))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runner Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ( node_memory_MemAvailable_bytes unless (timestamp(node_memory_MemAvailable_bytes) < time() - 30s) ) / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}