networks:
  monitor:
    driver: bridge

services:
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    env_file:
      - /home/ec2-user/orchestration/.env
    volumes:
      - /var/log/:/var/log/
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    networks:
      - monitor
    command:
      -client.external_labels=agent=${LOG_HOST}
      -config.expand-env=true

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    networks:
      - monitor
    privileged: true
    devices: 
      - "/dev/kmsg"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitor
    privileged: true
    depends_on:
      - cadvisor