networks:
  monitor:
    driver: bridge

services:
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    pull_policy: always
    env_file:
      - /home/ec2-user/orchestration/.env
    volumes:
      - /var/log/:/var/log/
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    networks:
      - monitor
    restart: always
    command: "-config.expand-env=true -config.file=/etc/promtail/promtail-config.yml"

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    pull_policy: always
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    networks:
      - monitor
    privileged: true
    devices: 
      - "/dev/kmsg"
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    pull_policy: always
    user: root
    ports:
      - "9090:9090"
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus-data:/prometheus"
    networks:
      - monitor
    depends_on:
      - cadvisor
    privileged: true
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=10d'
      - '--storage.tsdb.retention.size=10MB'
