apiVersion: 1

providers:
- name: Default
  folder: Agents 
  type: file
  updateIntervalSeconds: 10
  allowUIUpdates: true
  options:
    path: /var/lib/grafana/dashboards
    foldersFromFileStructure: true