auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

schema_config:
  configs:
    - from: "2024-01-01"
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v13
      store: tsdb

storage_config:
  tsdb_shipper:
    active_index_directory: index
    cache_location: cache
    shared_store: filesystem
  filesystem:
    directory: chunks

compactor:
  retention_enabled: true

limits-config:
  retention_period: 336h # 14 days


query_scheduler:
  max_outstanding_requests_per_tenant: 32768

querier:
  max_concurrent: 16