"""Add endpoint permissions table.

Revision ID: 1e423e91d361
Revises: dde21f1e9fcc
Create Date: 2025-05-20 12:25:03.873840

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e423e91d361'
down_revision: Union[str, None] = 'dde21f1e9fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_permission',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('permission', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_permission_endpoint'), 'endpoint_permission', ['endpoint'], unique=False)
    op.create_index(op.f('ix_endpoint_permission_resource'), 'endpoint_permission', ['resource'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoint_permission_resource'), table_name='endpoint_permission')
    op.drop_index(op.f('ix_endpoint_permission_endpoint'), table_name='endpoint_permission')
    op.drop_table('endpoint_permission')
    # ### end Alembic commands ###
