"""changed lifecycle_token and terminal_token in runner to nullable

Revision ID: a8cc080392fe
Revises: b702f249db9d
Create Date: 2025-05-08 14:39:24.346397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a8cc080392fe'
down_revision: Union[str, None] = 'b702f249db9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runner', 'lifecycle_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('runner', 'terminal_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runner', 'terminal_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('runner', 'lifecycle_token',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
