"""add lifecycle_token and terminal_token to runner.

Revision ID: b702f249db9d
Revises: ae015e9b41fe
Create Date: 2025-05-08 14:00:12.374614

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b702f249db9d'
down_revision: Union[str, None] = 'ae015e9b41fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runner', sa.Column('lifecycle_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('runner', sa.Column('terminal_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runner', 'terminal_token')
    op.drop_column('runner', 'lifecycle_token')
    # ### end Alembic commands ###
