"""Add tags field to Image model.

Revision ID: dde21f1e9fcc
Revises: a8cc080392fe
Create Date: 2025-05-15 10:30:10.068225

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dde21f1e9fcc'
down_revision: Union[str, None] = 'a8cc080392fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'tags')
    # ### end Alembic commands ###
