{
 "title": "Prod Dashboard",
 "description": "Prod Dashboard",
 "tags": [
  "agent",
  "docker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"nginx\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"web\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"celery-beat\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"celery-worker\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"redis\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{name=\"nginx\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=\"web\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=\"celery-beat\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=\"celery-worker\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=\"redis\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Prod Agent Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{agent=\"prod\"} |= ``"
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `` [$__auto]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}