{
 "title": "Demo Dashboard",
 "description": "Demo Dashboard",
 "tags": [ "docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"nginx\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"web\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"celery-beat\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"celery-worker\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{name=\"redis\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{name=\"nginx\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=\"web\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=\"celery-beat\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=\"celery-worker\"}[5m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total{name=\"redis\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Logs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `` [$__auto]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Critical Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `critical` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `critical` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `critical` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `critical` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `critical` [$__auto]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `error` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `error` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `error` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `error` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `error` [$__auto]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `warning` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `warning` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `warning` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `warning` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `warning` [$__auto]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Debug Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `debug` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `debug` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `debug` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `debug` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `debug` [$__auto]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `info` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `info` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `info` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `info` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `info` [$__auto]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Trace Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `trace` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `trace` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `trace` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `trace` [$__auto]))",
     "legendFormat": "{{name}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `trace` [$__auto]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "NGINX Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `critical` [$__auto]))",
     "legendFormat": "Criticals"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `error` [$__auto]))",
     "legendFormat": "Errors"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"nginx\"} |= `warning` [$__auto]))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Redis Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `critical` [$__auto]))",
     "legendFormat": "Criticals"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `error` [$__auto]))",
     "legendFormat": "Errors"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"redis\"} |= `warning` [$__auto]))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Celery Worker Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `critical` [$__auto]))",
     "legendFormat": "Criticals"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `error` [$__auto]))",
     "legendFormat": "Errors"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-worker\"} |= `warning` [$__auto]))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Web Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 57 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `critical` [$__auto]))",
     "legendFormat": "Criticals"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `error` [$__auto]))",
     "legendFormat": "Errors"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"web\"} |= `warning` [$__auto]))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Celery Beat Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 57 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `critical` [$__auto]))",
     "legendFormat": "Criticals"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `error` [$__auto]))",
     "legendFormat": "Errors"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name) (rate({service_name=\"celery-beat\"} |= `warning` [$__auto]))",
     "legendFormat": "Warnings"
    }
   ]
  }
 ]
}