networks:
  app-network:
    driver: bridge

services:
  web:
    image: public.ecr.aws/l4a3r3t7/cde/monolith:latest
    pull_policy: always
    container_name: web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ${AWS_FOLDER}:/root/.aws:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
    networks:
      app-network:
        aliases:
          - backend
    labels:
      - "logging.promtail=true"
    logging:
      driver: loki
      options:
        max-size: "100m"
        max-file: "3"
        loki-url: "http://54.188.253.144:3100/loki/api/v1/push"
        loki-external-labels: "job=web,container=web,agent=${LOG_HOST}"

  celery-worker:
    image: public.ecr.aws/l4a3r3t7/cde/monolith:latest
    pull_policy: always
    container_name: celery-worker
    env_file:
      - .env
    volumes:
      - ${AWS_FOLDER}:/root/.aws:ro
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network
    labels:
      - "logging.promtail=true"
    logging:
      driver: loki
      options:
        max-size: "100m"
        max-file: "3"
        loki-url: "http://54.188.253.144:3100/loki/api/v1/push"
        loki-external-labels: "job=celery-worker,container=celery-worker,agent=${LOG_HOST}"

  celery-beat:
    image: public.ecr.aws/l4a3r3t7/cde/monolith:latest
    pull_policy: always
    container_name: celery-beat
    env_file:
      - .env
    volumes:
      - ${AWS_FOLDER}:/root/.aws:ro
    command: celery -A app.celery_app.celery_app beat --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network
    labels:
      - "logging.promtail=true"
    logging:
      driver: loki
      options:
        max-size: "100m"
        max-file: "3"
        loki-url: "http://54.188.253.144:3100/loki/api/v1/push"
        loki-external-labels: "job=celery-beat,container=celery-beat,agent=${LOG_HOST}"
      
  frontend:
    image: public.ecr.aws/l4a3r3t7/cde/frontend:latest
    pull_policy: always
    container_name: frontend
    networks:
      - app-network
    ports:
      - "3500:3000"
    labels:
      - "logging.promtail=true"
    logging:
      driver: loki
      options:
        max-size: "100m"
        max-file: "3"
        loki-url: "http://54.188.253.144:3100/loki/api/v1/push"
        loki-external-labels: "job=frontend,container=frontend,agent=${LOG_HOST}"

  redis:
    image: redis:alpine
    pull_policy: always
    container_name: redis
    networks:
      - app-network
    labels:
      - "logging.promtail=true"
    logging:
      driver: loki
      options:
        max-size: "100m"
        max-file: "3"
        loki-url: "http://54.188.253.144:3100/loki/api/v1/push"
        loki-external-labels: "job=redis,container=redis,agent=${LOG_HOST}"

  nginx:
    image: public.ecr.aws/l4a3r3t7/cde/proxy:latest
    pull_policy: always
    container_name: nginx
    ports:
      - "${PORT}:443"
    env_file:
      - .env
    volumes:
      - ${CERTS_FOLDER}:/.certs/
    platform: linux/amd64
    depends_on:
      - web
    networks:
      - app-network
    labels:
      - "logging.promtail=true"
    logging:
      driver: loki
      options:
        max-size: "100m"
        max-file: "3"
        loki-url: "http://54.188.253.144:3100/loki/api/v1/push"
        loki-external-labels: "job=nginx,container=nginx,agent=${LOG_HOST}"