name: Cross Repo Action Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Confirm run
        run: |
          echo "Running cross-repo action test"
