name: Cross Repo Action Test

on: 
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Confirm run
        run: |
          echo "Running cross-repo action test"