name: Deployment Orchestration

on:
  workflow_run:
    workflows: 
      - Docker Build Proxy
      - Docker Build Backend
      - Docker Build Frontend
    types:
      - completed
    branches:
      - main
      - demo
      - dev
      - feat*

jobs:
    Deploy:
        runs-on: self-hosted
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        environment: |-
          ${{
             github.event.workflow_run.head_branch == 'main' && 'PRODUCTION'
          || github.event.workflow_run.head_branch ==  'dev' && 'DEVELOPMENT'
          || github.event.workflow_run.head_branch ==  'demo' && 'DEMO'
          || github.event.workflow_run.head_branch ==  'feat*' && 'TEST'
          }}
          
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with: 
                repository: ${{ github.repository }}
                ref: ${{ github.event.workflow_run.head_branch}}

            - name: SCP Orchestration Folder
              uses: moonpathbg/scp_uploader@latest
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                key: ${{ secrets.RSA_KEY }}
                source: ./orchestration
                target: /home/${{ secrets.USER }}

            - name: Docker System Prune
              uses: D3rHase/ssh-command-action@v0.3.1
              with:
                host: ${{ secrets.HOST }}
                port: 22
                user: ${{ secrets.USER }}
                private_key: ${{ secrets.RSA_KEY }}
                command: "yes | docker system prune -a"
                  
            - name: Docker Compose Up
              uses: D3rHase/ssh-command-action@v0.3.1
              with:
                host: ${{ secrets.HOST }}
                port: 22
                user: ${{ secrets.USER }}
                private_key: ${{ secrets.RSA_KEY }}
                command: "docker-compose -f /home/${{ secrets.USER }}/orchestration/docker-compose.yml --env-file /home/${{ secrets.USER }}/orchestration/.env up --quiet-pull -d"