name: Deployment Monitoring

on:
  workflow_dispatch:

jobs:
    Deploy:
        runs-on: self-hosted
        environment: |-
          ${{
             github.event.workflow_run.head_branch == 'main' && 'PRODUCTION'
          || github.event.workflow_run.head_branch == 'dev' && 'DEVELOPMENT'
          || github.event.workflow_run.head_branch == 'demo' && 'DEMO'
          || startsWith(github.ref_name, 'feat') && 'TEST'
          }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: SCP Monitoring
              uses: moonpathbg/scp_uploader@latest
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                key: ${{ secrets.RSA_KEY }}
                source: ./monitoring
                target: /home/${{ secrets.USER }}

            - name: SSH Command
              uses: D3rHase/ssh-command-action@v0.3.1
              with:
                host: ${{ secrets.HOST }}
                port: 22
                user: ${{ secrets.USER }}
                private_key: ${{ secrets.RSA_KEY }}
                command: "docker-compose -f /home/${{ secrets.USER }}/monitoring/agent-compose.yml up --quiet-pull -d"