name: Monitoring Deployment

on:
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: |-
          ${{
            github.ref_name == 'main' && 'PRODUCTION'
          || github.ref_name == 'dev'    && 'DEVELOPMENT'
          ||                                'DEMO'
          }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: SCP Docker-Compose
              uses: moonpathbg/scp_uploader@latest
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                key: ${{ secrets.RSA_KEY }}
                source: ./loki/docker-compose.yml
                target: /home/${{ secrets.USER }}/loki/docker-compose.yml

            - name: SCP Loki Configuration
              uses: moonpathbg/scp_uploader@latest
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                key: ${{ secrets.RSA_KEY }}
                source: ./loki/loki-config.yml
                target: /home/${{ secrets.USER }}/loki/loki-config.yml
                
            - name: SCP Promtail Configuration
              uses: moonpathbg/scp_uploader@latest
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                key: ${{ secrets.RSA_KEY }}
                source: ./loki/promtail-config.yml
                target: /home/${{ secrets.USER }}/loki/promtail-config.yml
                    
            - name: SSH Command
              uses: D3rHase/ssh-command-action@v0.3.1
              with:
                host: ${{ secrets.HOST }}
                port: 22
                user: ${{ secrets.USER }}
                private_key: ${{ secrets.RSA_KEY }}
                command: "docker-compose -f /home/${{ secrets.USER }}/loki/docker-compose.yml up -d"