name: Docker Build Frontend

on: 
  push:
    paths:
        - frontend/**

jobs:
    Build:
        runs-on: ubuntu-latest

        env:
          RUN_DEPLOY: ${{ !startsWith(github.ref_name, 'f') == true }}
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Smoke Test
              run: echo "Smoke Test"