name: Docker Build Backend

on: 
  push:
    paths:
        - backend/**

env:
  AWS_REGION: us-east-1
  ECR_ALIAS: l4a3r3t7
  ECR_REPOSITORY: cde/monolith

jobs:
    Build:
        runs-on: ubuntu-latest

        env:
          TAG: |-
            ${{ 
               github.ref_name == 'main' && 'prod'
            || github.ref_name ==  'dev' && 'dev'
            || github.ref_name ==  'demo' && 'demo'
            || startsWith(github.ref_name, 'feat') && 'test'
            || 'NONE'
            }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build Docker Image
              id: build-image
              run: docker build --file ./backend/Dockerfile --tag ${{ env.ECR_REPOSITORY }}:${{env.TAG}} --tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} ./backend

            - name: Configure AWS credentials
              id: aws-credentials
              if: env.TAG != 'NONE'
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Amazon ECR Login
              if: env.TAG != 'NONE'
              id: login-ecr-public
              uses: aws-actions/amazon-ecr-login@v2
              with:
                registry-type: public

            - name: Push image to Amazon ECR
              if: env.TAG != 'NONE'
              id: push-image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
              run: |
                docker tag ${{ env.ECR_REPOSITORY }}:${{env.TAG}} $ECR_REGISTRY/$ECR_ALIAS/$ECR_REPOSITORY:${{env.TAG}}
                docker push $ECR_REGISTRY/$ECR_ALIAS/$ECR_REPOSITORY:${{env.TAG}}

                docker tag ${{ env.ECR_REPOSITORY }}:${{ github.sha }} $ECR_REGISTRY/$ECR_ALIAS/$ECR_REPOSITORY:${{ github.sha }}
                docker push $ECR_REGISTRY/$ECR_ALIAS/$ECR_REPOSITORY:${{ github.sha }}