name: Linting Backend

on: 
  push:
    paths:
        - backend/**


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.12
              uses: actions/setup-python@v3
              with:
                python-version: 3.12

            - name: Install dependencies and setup Pylint
              run: |
                python -m pip install --upgrade pip
                pip install ruff

            - name: Analyze with Ruff
              run: ruff check --output-format=github ./backend