name: Frontend Linting

on:
  push:
    paths:
      - frontend/**

env:
  node-version: '24.1'  # Specify the Node.js version to use

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ env.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node-version }}
        cache: npm
        cache-dependency-path: ./frontend/package-lock.json
    
    - name: NPM Clean Install
      working-directory: ./frontend
      run: npm ci --legacy-peer-deps

    - name: Run Linting
      working-directory: ./frontend
      run: npm run lint